spring:
  datasource:
    url: "jdbc:mysql://localhost/jwt"
    username: "root"
    password: "show0715!"    # ???
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    #    lettuce:
    #      pool:
    #        max-active: 10
    #        max-idle: 10
    #        min-idle: 2
    port: 6379
    host: localhost
#    password: 'abcde'

jwt:
  header: Authorization
  # HS512 ( 512bit = 64byte secret key )
  # HS256
#  secret: {secret key}
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  access-token-validity-in-seconds: 1800
#  refresh-token-validity-in-seconds: 604800
  # 테스트로 1분 / 10분
  access-token-validity-in-seconds: 30
  refresh-token-validity-in-seconds: 600

#  token-validity-in-seconds: 86400

logging:
  level:
    com.jwt: DEBUG
